name: Issue Verification Helper

on:
  pull_request:
    types: [closed]

jobs:
  remind-to-verify:
    runs-on: ubuntu-latest
    # Only run if PR was merged and has claude-generated label
    if: github.event.pull_request.merged == true

    steps:
      - name: Check if PR has claude-generated label
        id: check-label
        uses: actions/github-script@v7
        with:
          script: |
            const { data: labels } = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            const hasClaudeLabel = labels.some(label => label.name === 'claude-generated');
            return hasClaudeLabel;

      - name: Find linked issues
        if: steps.check-label.outputs.result == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            // Get PR body and extract issue references
            const prBody = context.payload.pull_request.body || '';
            const issueRegex = /#(\d+)|https:\/\/github\.com\/[^\/]+\/[^\/]+\/issues\/(\d+)/g;
            const matches = [...prBody.matchAll(issueRegex)];
            const issueNumbers = matches.map(m => m[1] || m[2]).filter(Boolean);

            // Comment on each linked issue
            for (const issueNumber of issueNumbers) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: parseInt(issueNumber),
                body: `🎉 **PR #${context.issue.number} has been merged!**

## ⚠️ Action Required - Verify the Fix

@jessicatmt Please test that this fix actually resolves the issue:

1. **Test the fix** on the deployed site or locally
2. **Verify** the original problem is resolved
3. **Check** for any side effects or regressions

Once verified, you can:
- ✅ Close this issue with a comment: "Verified - works as expected"
- ⚠️ Re-open if the issue persists: "Issue still occurs because..."

**Auto-closing has been disabled** - manual verification required.`
              });

              // Add label to track verification status
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: parseInt(issueNumber),
                labels: ['needs-verification', 'pr-merged']
              });
            }
